light:
- platform: group
  name: Living room
  entities:
  - light.reading_corner
  - light.bookcase
- platform: group
  name: Bedroom
  entities:
  - light.hue_color_lamp_1
- platform: group
  name: Reading Corner
  entities:
  - light.hue_color_lamp_3
  - light.hue_color_lamp_4
- platform: group
  name: Bookcase
  entities:
  - light.dimmable_light_1
